# Generated by Django 2.2.10 on 2020-05-13 21:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
                ('board', models.CharField(default='', max_length=1225)),
                ('solved', models.CharField(default='', max_length=1225)),
                ('optional_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
                ('total_blocks', models.IntegerField(default=25)),
                ('valid', models.BooleanField(default=False)),
                ('is_copy', models.BooleanField(default=False)),
                ('indices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('clues', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CrosswordError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msg', models.CharField(default='', max_length=10240)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('hu', 'Hungarian')], max_length=200)),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='crosswords.Dictionary')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dictionary',
            constraint=models.UniqueConstraint(fields=('language',), name='unique_dictionary'),
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='crosswords.Word'),
        ),
        migrations.AddField(
            model_name='crossworderror',
            name='crossword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='crosswords.Crossword'),
        ),
        migrations.AddField(
            model_name='crossword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswords', to='crosswords.Dictionary'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('dictionary', 'word'), name='unique_word'),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('word', 'definition'), name='unique_definition'),
        ),
    ]
