# Generated by Django 2.2.10 on 2020-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0003_auto_20200513_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('hu', 'Hungarian')], max_length=200),
        ),
    ]
