# Generated by Django 2.2.10 on 2020-05-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0006_auto_20200513_1748'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition',
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('language', 'word', 'definition'), name='unique_definition'),
        ),
    ]
